version: '3'

services: 
    app:
        container_name: remote_app
        restart: always
        build: .
        ports: 
            - '90:3000'
        # links: 
        #     - mongo
        environment:
            - "DB=${DB}"
            - "DB_NAME=${DB_NAME}"
            - "DB_APP_NAME=${DB_APP_NAME}"
            - "DB_PORT=${DB_PORT}"
            - "APP_PORT=${APP_PORT}"
        volumes:
            - ~/Public/RemoteApp:/app:rw
            - /app/node_modules
        privileged: true
    # mongo:
    #     container_name: mongo_remote
    #     image: mongo
    #     ports: 
    #         - '90:6000'
    #     ports: 
    #         - '27017:27017'
    #     volumes:
    #         - ~/Public/RemoteApp/data:/data/db:rw




# wygląda na to, że chrom ani chromium nie jest instalowany.
# próbowałem zrobić to w Dockerfile'u ale nie działało (niby apt mu nie pasuje (apt-get też))
# pózniej próbowałem w kontenerze już po jego stworzeniu ale przy wget było, że Permission Denied